### ISSUE TITLE
OSS Gate Workshop: 東京: 2017-05-29: Oshiumi: ChainerRL: Work log

### ISSUE THREAD

**Issue by Oshiumi** [vividmuimui/workshop#5]
These are my work logs (in Japanese) for "OSS Gate",
a workshop designed to encourage contributions to open-source software.

---

- この issue のタイトルを  
「OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log」  
の形式でつけてください
- 例：  
「OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log」
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

---

OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業：（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by Oshiumi** [comment]
リポジトリを見つけた
https://github.com/pfnet/chainerrl

**Comment by Oshiumi** [comment]
installationあった
https://github.com/pfnet/chainerrl#installation

**Comment by Oshiumi** [comment]
`pip install chainerrl`

**Comment by Oshiumi** [comment]
エラー！
```
Collecting chainerrl
Requirement already satisfied: statistics in /usr/local/lib/python2.7/site-packages (from chainerrl)
Requirement already satisfied: chainer>=1.20.0.1 in /usr/local/lib/python2.7/site-packages (from chainerrl)
Requirement already satisfied: scipy in /usr/local/lib/python2.7/site-packages (from chainerrl)
Requirement already satisfied: fastcache in /usr/local/lib/python2.7/site-packages (from chainerrl)
Requirement already satisfied: future in /usr/local/lib/python2.7/site-packages (from chainerrl)
Requirement already satisfied: cached-property in /usr/local/lib/python2.7/site-packages (from chainerrl)
Collecting atari-py (from chainerrl)
  Using cached atari-py-0.1.1.tar.gz
Requirement already satisfied: pillow in /usr/local/lib/python2.7/site-packages (from chainerrl)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python2.7/site-packages (from chainerrl)
Requirement already satisfied: gym>=0.7.3 in /usr/local/lib/python2.7/site-packages (from chainerrl)
Collecting funcsigs (from chainerrl)
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Requirement already satisfied: docutils>=0.3 in /usr/local/lib/python2.7/site-packages (from statistics->chainerrl)
Requirement already satisfied: nose in /usr/local/lib/python2.7/site-packages (from chainer>=1.20.0.1->chainerrl)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python2.7/site-packages (from chainer>=1.20.0.1->chainerrl)
Requirement already satisfied: filelock in /usr/local/lib/python2.7/site-packages (from chainer>=1.20.0.1->chainerrl)
Requirement already satisfied: protobuf>=2.6.0 in /usr/local/lib/python2.7/site-packages (from chainer>=1.20.0.1->chainerrl)
Requirement already satisfied: olefile in /usr/local/lib/python2.7/site-packages (from pillow->chainerrl)
Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python2.7/site-packages (from gym>=0.7.3->chainerrl)
Requirement already satisfied: requests>=2.0 in /usr/local/lib/python2.7/site-packages (from gym>=0.7.3->chainerrl)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/site-packages (from protobuf>=2.6.0->chainer>=1.20.0.1->chainerrl)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/site-packages (from requests>=2.0->gym>=0.7.3->chainerrl)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/site-packages (from requests>=2.0->gym>=0.7.3->chainerrl)
Requirement already satisfied: urllib3<1.22,>=1.21.1 in /usr/local/lib/python2.7/site-packages (from requests>=2.0->gym>=0.7.3->chainerrl)
Requirement already satisfied: idna<2.6,>=2.5 in /usr/local/lib/python2.7/site-packages (from requests>=2.0->gym>=0.7.3->chainerrl)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python2.7/site-packages (from setuptools->protobuf>=2.6.0->chainer>=1.20.0.1->chainerrl)
Requirement already satisfied: appdirs>=1.4.0 in /usr/local/lib/python2.7/site-packages (from setuptools->protobuf>=2.6.0->chainer>=1.20.0.1->chainerrl)
Requirement already satisfied: pyparsing in /usr/local/lib/python2.7/site-packages (from packaging>=16.8->setuptools->protobuf>=2.6.0->chainer>=1.20.0.1->chainerrl)
Building wheels for collected packages: atari-py
  Running setup.py bdist_wheel for atari-py ... error
  Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/h5/4h3gfc5x2zvbsv4r4h_j6j500000gp/T/pip-build-a_KZQy/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/h5/4h3gfc5x2zvbsv4r4h_j6j500000gp/T/tmpY_Oqxppip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  mkdir -p build && cd build && cmake .. && make -j4
  /bin/sh: cmake: command not found
  make: *** [build] Error 127
  Could not build atari-py: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '3']' returned non-zero exit status 2. (HINT: are you sure cmake is installed? You might also be missing a library. Atari-py requires: zlib [installable as 'apt-get install zlib1g-dev' on Ubuntu].)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/h5/4h3gfc5x2zvbsv4r4h_j6j500000gp/T/pip-build-a_KZQy/atari-py/setup.py", line 36, in <module>
      tests_require=['nose2']
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/h5/4h3gfc5x2zvbsv4r4h_j6j500000gp/T/pip-build-a_KZQy/atari-py/setup.py", line 16, in run
      subprocess.check_call(cmd)
    File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '3']' returned non-zero exit status 2

  ----------------------------------------
  Failed building wheel for atari-py
  Running setup.py clean for atari-py
Failed to build atari-py
Installing collected packages: atari-py, funcsigs, chainerrl
  Running setup.py install for atari-py ... error
    Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/h5/4h3gfc5x2zvbsv4r4h_j6j500000gp/T/pip-build-a_KZQy/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/h5/4h3gfc5x2zvbsv4r4h_j6j500000gp/T/pip-IhMb0_-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    mkdir -p build && cd build && cmake .. && make -j4
    /bin/sh: cmake: command not found
    make: *** [build] Error 127
    Could not build atari-py: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '3']' returned non-zero exit status 2. (HINT: are you sure cmake is installed? You might also be missing a library. Atari-py requires: zlib [installable as 'apt-get install zlib1g-dev' on Ubuntu].)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h5/4h3gfc5x2zvbsv4r4h_j6j500000gp/T/pip-build-a_KZQy/atari-py/setup.py", line 36, in <module>
        tests_require=['nose2']
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/h5/4h3gfc5x2zvbsv4r4h_j6j500000gp/T/pip-build-a_KZQy/atari-py/setup.py", line 16, in run
        subprocess.check_call(cmd)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'build', '-C', 'atari_py/ale_interface', '-j', '3']' returned non-zero exit status 2

    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/h5/4h3gfc5x2zvbsv4r4h_j6j500000gp/T/pip-build-a_KZQy/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/h5/4h3gfc5x2zvbsv4r4h_j6j500000gp/T/pip-IhMb0_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/h5/4h3gfc5x2zvbsv4r4h_j6j500000gp/T/pip-build-a_KZQy/atari-py/
```

**Comment by Oshiumi** [comment]
setuptoolsが古い？

**Comment by Oshiumi** [comment]
`pip install --upgrade setuptools`

**Comment by Oshiumi** [comment]
upgradeはできたけどchainerrlはインストールできず

**Comment by Oshiumi** [comment]
requirementsがあった
https://github.com/pfnet/chainerrl/blob/master/requirements.txt

**Comment by Oshiumi** [comment]
gymが入ってない！

**Comment by Oshiumi** [comment]
pillowもない！

**Comment by Oshiumi** [comment]
`pip install gym pillow`

**Comment by Oshiumi** [comment]
Failed building wheel for atari-pyでググる

**Comment by Oshiumi** [comment]
cmakeも必要っぽい
https://paper.dropbox.com/doc/ChainerRL-Quickstart-Guide-JP-vk2HUIl5GbrYnLsYwLazr
`brew install cmake`

**Comment by Oshiumi** [comment]
インストールできた！！！

**Comment by Oshiumi** [comment]
ここを見てテストをしてみる
https://github.com/pfnet/chainerrl/blob/master/CONTRIBUTING.md

**Comment by Oshiumi** [comment]
`easy_install nose`

**Comment by Oshiumi** [comment]
macOS Sierra version 10.12.4 で
`/bin/sh: cmake: command not found`
と言われた。
Mac ではcmakeがデフォルトで入ってないのでRequirementに一応書いておいて欲しい。
`brew install cmake`
で入れることができる。

**Comment by Oshiumi** [comment]
Hi,
I failed to install with error:
 `/bin/sh: cmake: command not found`
in macOS Sierra version 10.12.4.

atari-py require cmake.
https://github.com/openai/atari-py

**Comment by Oshiumi** [comment]
残りはreadme変更してから書きます！

**Comment by rastamhadi** [comment]
```diff
  Hi,
- I failed to install with error:
+ I had some trouble installing ChainerRL on my MacBook (macOS Sierra version 10.12.4).
- /bin/sh: cmake: command not found
- in macOS Sierra version 10.12.4.
```

`I failed` だと自分を責めてる感じでちょっと重くなってたので
`had some trouble` 椀曲表現で柔らかくしておきました。

```diff
+ The error I got from `pip install chainerrl` was:
+ /bin/sh: cmake: command not found
```

エラーはどこから出た？ってなっちゃうから
`pip` コマンド明記しておきました。

```
atari-py require cmake.
https://github.com/openai/atari-py
```

atari-py の話をするなら
atari-py のところまでエラーの抜粋に含めたほうがいいかも？
何で atari-py の話になったかが分かるための繋ぎとして。

atari-py に触れない手もある。
続きをどう書くかによって。
